### ISSUE TITLE
write_targets creates wrong filename during pre-processing from openptv-python

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv#111]
write_targets creates wrong filename during pre-processing from openptv-python, where `jw_ptv.c` sends frame = 0. the name comes out like `cam0.tif0000_targets`. write_target has to recognize a special case from pre-processing stage where the filename should not be related to frame, when frame = 0 (actually it is supposedly should be -999 or a special flag in addition to the frame number).

**Comment by yosefm** [comment]
Why is that a problem?
