### ISSUE TITLE
python setup.py install issue

### ISSUE THREAD

**Issue by pinghanchu** [OpenPTV/openptv#145]
Hi,
I follow the instruction to install openptv.
http://openptv-python.readthedocs.io/en/latest/installation_instruction.html

However, I had a trouble at this step:
"Install Python bindings for the library (installs `optv` module):"

Here is the error I got when "python setup.py install"
--------------------------------------------------------------------
running install
running build
running build_py
running build_ext
skipping 'optv/tracking_framebuf.c' Cython extension (up-to-date)
building 'optv.tracking_framebuf' extension
gcc -fno-strict-aliasing -I/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/lib/python2.7/site-packages/numpy/core/include -I. -I/anaconda/include/python2.7 -c optv/tracking_framebuf.c -o build/temp.macosx-10.6-x86_64-2.7/optv/tracking_framebuf.o
optv/tracking_framebuf.c:482:10: fatal error: 'optv/vec_utils.h' file not found
#include "optv/vec_utils.h"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
--------------------------------------------------------------------

The previous step seems to be fine when "python setup.py build_ext --inplace -I/usr/local/include -L/usr/local/lib":
--------------------------------------------------------------------
running build_ext
skipping 'optv/tracking_framebuf.c' Cython extension (up-to-date)
skipping 'optv/parameters.c' Cython extension (up-to-date)
skipping 'optv/calibration.c' Cython extension (up-to-date)
skipping 'optv/transforms.c' Cython extension (up-to-date)
skipping 'optv/imgcoord.c' Cython extension (up-to-date)
skipping 'optv/image_processing.c' Cython extension (up-to-date)
skipping 'optv/correspondences.c' Cython extension (up-to-date)
skipping 'optv/segmentation.c' Cython extension (up-to-date)
skipping 'optv/epipolar.c' Cython extension (up-to-date)
skipping 'optv/tracker.c' Cython extension (up-to-date)
skipping 'optv/orientation.c' Cython extension (up-to-date)
--------------------------------------------------------------------

I also check the location of optv at /usr/local/include/optv/vec_utils.h 

Any suggestion? I use MacOSX10.12.6. Thanks.

**Comment by alexlib** [comment]
What was the output of the `liboptv` installation? did it install `vec_utils` ?
Indeed it is strange that it found the file when compiled the extension and not when it's installed. I can suggest to contact me offline and set up a Teamviewer session (remote access to your machine) to look into the problem closely.

**Comment by pinghanchu** [comment]
Okay, I will email to you for the setup of teamviewer.

It seems to me I've installed "liboptv". Here is the output for installing liboptv:
---------------------
$cmake ../
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   optv

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/pchu/openpty/openptv-master/liboptv/build
---------------------
$ make
[100%] Built target optv
---------------------
$make verify

100% tests passed, 0 tests failed out of 16

Total Test time (real) =   2.01 sec
[100%] Built target verify
---------------------
$ make install
[100%] Built target optv
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/include/optv/
-- Up-to-date: /usr/local/include/optv//calibration.h
-- Up-to-date: /usr/local/include/optv//correspondences.h
-- Up-to-date: /usr/local/include/optv//epi.h
-- Up-to-date: /usr/local/include/optv//image_processing.h
-- Up-to-date: /usr/local/include/optv//imgcoord.h
-- Up-to-date: /usr/local/include/optv//lsqadj.h
-- Up-to-date: /usr/local/include/optv//multimed.h
-- Up-to-date: /usr/local/include/optv//orientation.h
-- Up-to-date: /usr/local/include/optv//parameters.h
-- Up-to-date: /usr/local/include/optv//ray_tracing.h
-- Up-to-date: /usr/local/include/optv//segmentation.h
-- Up-to-date: /usr/local/include/optv//sortgrid.h
-- Up-to-date: /usr/local/include/optv//track.h
-- Up-to-date: /usr/local/include/optv//tracking_frame_buf.h
-- Up-to-date: /usr/local/include/optv//tracking_run.h
-- Up-to-date: /usr/local/include/optv//trafo.h
-- Up-to-date: /usr/local/include/optv//vec_utils.h
-- Installing: /usr/local/lib/liboptv.dylib

**Comment by alexlib** [comment]
We didn't find a bug, I successfully installed opentpv on that machine using remote control
