### ISSUE TITLE
there is no docstring about eps0 - is it in mm? is it in pixels? 

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv#148]
https://github.com/OpenPTV/openptv/blob/7fb3296c6746f25222b7ac00213c240ea0218f99/liboptv/src/parameters.c#L203

**Comment by alexlib** [comment]
Please Yosef - we are not sure why eps0 is in mm and it measures epipolar band in the image space which is apparently in pixels. Wouldn't be more logical to have it in pixels as well?

**Comment by yosefm** [comment]
The epipolar comparison is done in flat-image coordinates, which are metric (see `docs/ptv_coordinates.lyx`). The comparison itself is in `epi.c : find_candidate()`. there you can see what it compares against. 

I didn't choose it, BTW - it was like that in the old code as far as I recall.

**Comment by yosefm** [comment]
Now, you might want to add a comment about it in parameters.h at least.

**Comment by alexlib** [comment]
resolved in #149
