### ISSUE TITLE
backward compatibility for parameters.c

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv#34]
The parameters.c in liboptv is not backward compatible in terms of I/O routine that reads parameters: if number of cameras is less than 4, then the file shall include only the names of the images for the given number of cameras. This is a good design, but then the new parameter files will not be readable by the Tcl/Tk version or older version of PyPTV. Therefore, the patch is suggested: 

https://github.com/alexlib/openptv/commit/67f5fa4f6d5b0bc1cbd7d2078b67f58f8c0ad349

**Comment by yosefm** [comment]
You're right. since the only reason we support the .par format is backward compat, I'll use this patch and soon I'll also make a PR when I'm not deep in my own stuff.

**Comment by alexlib** [comment]
recommend to merge
