### ISSUE TITLE
add -lrt on the Ubuntu 14.04 with Check installed by apt-get

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv#52]
On Ubuntu 14.04 Trusty 64 bit machines one has to modify the 

https://github.com/OpenPTV/openptv/blob/master/liboptv/tests/CMakeLists.txt#L32

line to: 

set(LIBS ${LIBS} -lm -pthread -lrt)

in order to run the unit tests with 

$$ make verify

**Comment by yosefm** [comment]
I think we handled this and can close the issue, right?
